name: automatically add new/reopened issue/PR to project
on:
    issues:
        types:
            - unassigned
    pull_request:
        types:
            - unassigned
jobs:
    createCard:
        runs-on: ubuntu-latest
        steps:
            - name: Create Project Card
              uses: peter-evans/create-or-update-project-card@v1.1.4
              with:
                  project-name: 後端進度
                  column-name: 會優先做
